# Generated by Django 6.0.2 on 2026-03-25 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='telemetryevent',
            name='active_seconds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='telemetryevent',
            name='idle_seconds',
            field=models.IntegerField(default=0),
        ),
    ]
