# Generated by Django 6.0.2 on 2026-04-02 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0003_telemetryevent_active_seconds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telemetryevent',
            name='build_failures',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='telemetryevent',
            name='build_runs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='telemetryevent',
            name='errors',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='telemetryevent',
            name='file_switches',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='telemetryevent',
            name='repeated_errors',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='telemetryevent',
            name='terminal_errors',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='telemetryevent',
            name='undo_count',
            field=models.IntegerField(default=0),
        ),
    ]
